# General configuration
seed: 0
dataset: smoke
root: ../../data/${dataset}/testing_data/
lr: 0.0001
batch_size: 16
check_every: 50
loss: MSE
latent_feats: 128

# Decoder Parameters
pos_feats: 120
g_feats: 128
hidden_layers: 4
hidden_features: 128