defaults:
  - common_train
  - _self_

encoder: PT
dir_weights: ./${encoder}/weights/
dir_outputs: ./${encoder}/outputs/
start_epoch: 0
epochs: 500
batch_size: 2

# Encoder Parameters
enc_layers: 3
knn_neighbors: 16
transformer_dim: 64
latent_feats: 128

# Network string
network_str: ${enc_layers}_${knn_neighbors}_${transformer_dim}