defaults:
  - common_train
  - _self_
  
encoder: GINO
dir_weights: ./${encoder}/weights/
dir_outputs: ./${encoder}/outputs/
batch_size: 4
start_epoch: 0
epochs: 500

# Encoder Parameters
gno_transform_type: nonlinear

# Network string
network_str: ${gno_transform_type}